version: '3.8'
services:
    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
        environment:
            - ACCEPT_EULA=Y
            - 'MSSQL_SA_PASSWORD=lesnaparola12#'
        ports:
            - '1433:1433'
        volumes:
            - 'sqldata:/var/opt/mssql'
        networks: 
            - 'taskboard_network'
    web_app:
        container_name: taskboard_app
        build:
            dockerfile: ./TaskBoard.WebApp/Dockerfile
#        image: lokumchev/taskboard_app
        ports:
            - '5000:80'
        restart: on-failure
        networks:
            - 'taskboard_network'
networks:
    taskboard_network:
        external: true
volumes:
    sqldata:
        external: true